### PR TITLE
Design!!

### LINKED ISSUE #13: Front-end-standardize-button-style

### LINKED ISSUE #30: Design (font, colors, placement etc)

### LINKED ISSUE #48: Update the design of BusinessValidScreen.js and BusinessInvalidScreen.js

### PR DESCRIPTION
**Pull request by maha8298**
# Creator / Commiter

## Mandatory

- [x] README is up to date
- [x] Assigned 2 reviewers
- [x] Documentation of the code has been done
- [x] Labels are correctly used
- [x] Project has been connected to this pull request
- [x] Issues solved by this pull request have been linked

## Optional

- [ ] Added tests with new implementations
- [ ] Proposed code has no tests yet

# Reviewer 1

## Mandatory

- [x] Commiter has checked all mandatory boxes
- [x] README is up to date
- [x] Code is correctly documented
- [x] Code follows style guide
- [x] Pull request is correctly labeled
- [x] Issues solved by this pull request have been linked

# Reviewer 2

## Mandatory

- [x] Commiter has checked all mandatory boxes
- [x] Reviewer 1 has checked all mandatory boxes
- [x] README is up to date
- [x] Code is correctly documented
- [x] Code follows style guide
- [x] Pull request is correctly labeled
- [x] Issues solved by this pull request have been linked

### Finally

- [ ] Merged repo to master

### CODE REVIEW

**Review by horrokotoj — CHANGES_REQUESTED** [review]
DS_Store needs to be removed and added to the gitignore-file.
This is some Mac os X stuff.

**Review by Lifen93 — APPROVED** [review]
Looks good!

**Review by Lifen93 — CHANGES_REQUESTED** [review]
To remove: DS_Store

**Review by Lifen93 — APPROVED** [review]
Nicely done!

**Review by horrokotoj — APPROVED** [review]

**Pull request merged**
