### PR TITLE
Implementing a timer on 15 seconds for updating qrString.

### LINKED ISSUE #45: Update the verification process
Needs to send the random qr-string and not the google user id.

### LINKED ISSUE #47: Implement timer for http-requests
Implement a timer instead of updatebuttons.

### PR DESCRIPTION
**Pull request by horrokotoj**
Implementing a timer on 60 seconds for updating certificats.

# Creator / Commiter

## Mandatory

- [x] README is up to date
- [x] Assigned 2 reviewers
- [x] Documentation of the code has been done
- [x] Labels are correctly used
- [x] Project has been connected to this pull request
- [x] Issues solved by this pull request have been linked

## Optional

- [ ] Added tests with new implementations
- [x] Proposed code has no tests yet

# Reviewer 1

## Mandatory

- [x] Commiter has checked all mandatory boxes
- [x] README is up to date
- [x] Code is correctly documented
- [x] Code follows style guide
- [x] Pull request is correctly labeled
- [x] Issues solved by this pull request have been linked

# Reviewer 2

## Mandatory

- [x] Commiter has checked all mandatory boxes
- [x] Reviewer 1 has checked all mandatory boxes
- [x] README is up to date
- [x] Code is correctly documented
- [x] Code follows style guide
- [x] Pull request is correctly labeled
- [x] Issues solved by this pull request have been linked

### Finally

- [ ] Merged repo to master

### CODE REVIEW

**Comment by horrokotoj** [comment]
This also uses the qr_string for the qr code.
This will work with the latest version of the server.

**Review by Lifen93 — CHANGES_REQUESTED** [review]
valid variable should be named isValid since its a bool. Plz update

**Comment by horrokotoj** [comment]
Request to change valid to isValid approved and commited.

**Review by Lifen93 — APPROVED** [review]
Thx! Looks good!

**Review by ebba-lowgren — APPROVED** [review]

**Pull request merged**
